/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppPacienteNuevoRouteImport } from './routes/_app.paciente.nuevo'
import { Route as AppPacienteIdRouteImport } from './routes/_app.paciente.$id'
import { Route as AppPacienteIdReporteRouteImport } from './routes/_app.paciente.$id.reporte'
import { Route as AppPacienteIdChequeoRouteImport } from './routes/_app.paciente.$id.chequeo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteNuevoRoute = AppPacienteNuevoRouteImport.update({
  id: '/paciente/nuevo',
  path: '/paciente/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdRoute = AppPacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdReporteRoute = AppPacienteIdReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => AppPacienteIdRoute,
} as any)
const AppPacienteIdChequeoRoute = AppPacienteIdChequeoRouteImport.update({
  id: '/chequeo',
  path: '/chequeo',
  getParentRoute: () => AppPacienteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppAppRoute
  '/paciente/$id': typeof AppPacienteIdRouteWithChildren
  '/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppAppRoute
  '/paciente/$id': typeof AppPacienteIdRouteWithChildren
  '/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/app': typeof AppAppRoute
  '/_app/paciente/$id': typeof AppPacienteIdRouteWithChildren
  '/_app/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/_app/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/_app/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/paciente/$id'
    | '/paciente/nuevo'
    | '/paciente/$id/chequeo'
    | '/paciente/$id/reporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/paciente/$id'
    | '/paciente/nuevo'
    | '/paciente/$id/chequeo'
    | '/paciente/$id/reporte'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/app'
    | '/_app/paciente/$id'
    | '/_app/paciente/nuevo'
    | '/_app/paciente/$id/chequeo'
    | '/_app/paciente/$id/reporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/nuevo': {
      id: '/_app/paciente/nuevo'
      path: '/paciente/nuevo'
      fullPath: '/paciente/nuevo'
      preLoaderRoute: typeof AppPacienteNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id': {
      id: '/_app/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof AppPacienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/reporte': {
      id: '/_app/paciente/$id/reporte'
      path: '/reporte'
      fullPath: '/paciente/$id/reporte'
      preLoaderRoute: typeof AppPacienteIdReporteRouteImport
      parentRoute: typeof AppPacienteIdRoute
    }
    '/_app/paciente/$id/chequeo': {
      id: '/_app/paciente/$id/chequeo'
      path: '/chequeo'
      fullPath: '/paciente/$id/chequeo'
      preLoaderRoute: typeof AppPacienteIdChequeoRouteImport
      parentRoute: typeof AppPacienteIdRoute
    }
  }
}

interface AppPacienteIdRouteChildren {
  AppPacienteIdChequeoRoute: typeof AppPacienteIdChequeoRoute
  AppPacienteIdReporteRoute: typeof AppPacienteIdReporteRoute
}

const AppPacienteIdRouteChildren: AppPacienteIdRouteChildren = {
  AppPacienteIdChequeoRoute: AppPacienteIdChequeoRoute,
  AppPacienteIdReporteRoute: AppPacienteIdReporteRoute,
}

const AppPacienteIdRouteWithChildren = AppPacienteIdRoute._addFileChildren(
  AppPacienteIdRouteChildren,
)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppPacienteIdRoute: typeof AppPacienteIdRouteWithChildren
  AppPacienteNuevoRoute: typeof AppPacienteNuevoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppPacienteIdRoute: AppPacienteIdRouteWithChildren,
  AppPacienteNuevoRoute: AppPacienteNuevoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
