/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppPacienteNuevoRouteImport } from './routes/_app.paciente.nuevo'
import { Route as AppPacienteIdIndexRouteImport } from './routes/_app.paciente.$id.index'
import { Route as AppPacienteIdSignosRouteImport } from './routes/_app.paciente.$id.signos'
import { Route as AppPacienteIdReporteRouteImport } from './routes/_app.paciente.$id.reporte'
import { Route as AppPacienteIdMedicamentosRouteImport } from './routes/_app.paciente.$id.medicamentos'
import { Route as AppPacienteIdChequeoRouteImport } from './routes/_app.paciente.$id.chequeo'
import { Route as AppPacienteIdCaidasRouteImport } from './routes/_app.paciente.$id.caidas'
import { Route as AppPacienteIdBitacorasRouteImport } from './routes/_app.paciente.$id.bitacoras'
import { Route as AppPacienteIdEscalasIndexRouteImport } from './routes/_app.paciente.$id.escalas.index'
import { Route as AppPacienteIdEscalasZaritRouteImport } from './routes/_app.paciente.$id.escalas.zarit'
import { Route as AppPacienteIdEscalasJenkinsRouteImport } from './routes/_app.paciente.$id.escalas.jenkins'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteNuevoRoute = AppPacienteNuevoRouteImport.update({
  id: '/paciente/nuevo',
  path: '/paciente/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdIndexRoute = AppPacienteIdIndexRouteImport.update({
  id: '/paciente/$id/',
  path: '/paciente/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdSignosRoute = AppPacienteIdSignosRouteImport.update({
  id: '/paciente/$id/signos',
  path: '/paciente/$id/signos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdReporteRoute = AppPacienteIdReporteRouteImport.update({
  id: '/paciente/$id/reporte',
  path: '/paciente/$id/reporte',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdMedicamentosRoute =
  AppPacienteIdMedicamentosRouteImport.update({
    id: '/paciente/$id/medicamentos',
    path: '/paciente/$id/medicamentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacienteIdChequeoRoute = AppPacienteIdChequeoRouteImport.update({
  id: '/paciente/$id/chequeo',
  path: '/paciente/$id/chequeo',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdCaidasRoute = AppPacienteIdCaidasRouteImport.update({
  id: '/paciente/$id/caidas',
  path: '/paciente/$id/caidas',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdBitacorasRoute = AppPacienteIdBitacorasRouteImport.update({
  id: '/paciente/$id/bitacoras',
  path: '/paciente/$id/bitacoras',
  getParentRoute: () => AppRoute,
} as any)
const AppPacienteIdEscalasIndexRoute =
  AppPacienteIdEscalasIndexRouteImport.update({
    id: '/paciente/$id/escalas/',
    path: '/paciente/$id/escalas/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacienteIdEscalasZaritRoute =
  AppPacienteIdEscalasZaritRouteImport.update({
    id: '/paciente/$id/escalas/zarit',
    path: '/paciente/$id/escalas/zarit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPacienteIdEscalasJenkinsRoute =
  AppPacienteIdEscalasJenkinsRouteImport.update({
    id: '/paciente/$id/escalas/jenkins',
    path: '/paciente/$id/escalas/jenkins',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppAppRoute
  '/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/paciente/$id/bitacoras': typeof AppPacienteIdBitacorasRoute
  '/paciente/$id/caidas': typeof AppPacienteIdCaidasRoute
  '/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/paciente/$id/medicamentos': typeof AppPacienteIdMedicamentosRoute
  '/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
  '/paciente/$id/signos': typeof AppPacienteIdSignosRoute
  '/paciente/$id/': typeof AppPacienteIdIndexRoute
  '/paciente/$id/escalas/jenkins': typeof AppPacienteIdEscalasJenkinsRoute
  '/paciente/$id/escalas/zarit': typeof AppPacienteIdEscalasZaritRoute
  '/paciente/$id/escalas/': typeof AppPacienteIdEscalasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppAppRoute
  '/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/paciente/$id/bitacoras': typeof AppPacienteIdBitacorasRoute
  '/paciente/$id/caidas': typeof AppPacienteIdCaidasRoute
  '/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/paciente/$id/medicamentos': typeof AppPacienteIdMedicamentosRoute
  '/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
  '/paciente/$id/signos': typeof AppPacienteIdSignosRoute
  '/paciente/$id': typeof AppPacienteIdIndexRoute
  '/paciente/$id/escalas/jenkins': typeof AppPacienteIdEscalasJenkinsRoute
  '/paciente/$id/escalas/zarit': typeof AppPacienteIdEscalasZaritRoute
  '/paciente/$id/escalas': typeof AppPacienteIdEscalasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/app': typeof AppAppRoute
  '/_app/paciente/nuevo': typeof AppPacienteNuevoRoute
  '/_app/paciente/$id/bitacoras': typeof AppPacienteIdBitacorasRoute
  '/_app/paciente/$id/caidas': typeof AppPacienteIdCaidasRoute
  '/_app/paciente/$id/chequeo': typeof AppPacienteIdChequeoRoute
  '/_app/paciente/$id/medicamentos': typeof AppPacienteIdMedicamentosRoute
  '/_app/paciente/$id/reporte': typeof AppPacienteIdReporteRoute
  '/_app/paciente/$id/signos': typeof AppPacienteIdSignosRoute
  '/_app/paciente/$id/': typeof AppPacienteIdIndexRoute
  '/_app/paciente/$id/escalas/jenkins': typeof AppPacienteIdEscalasJenkinsRoute
  '/_app/paciente/$id/escalas/zarit': typeof AppPacienteIdEscalasZaritRoute
  '/_app/paciente/$id/escalas/': typeof AppPacienteIdEscalasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/paciente/nuevo'
    | '/paciente/$id/bitacoras'
    | '/paciente/$id/caidas'
    | '/paciente/$id/chequeo'
    | '/paciente/$id/medicamentos'
    | '/paciente/$id/reporte'
    | '/paciente/$id/signos'
    | '/paciente/$id/'
    | '/paciente/$id/escalas/jenkins'
    | '/paciente/$id/escalas/zarit'
    | '/paciente/$id/escalas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/paciente/nuevo'
    | '/paciente/$id/bitacoras'
    | '/paciente/$id/caidas'
    | '/paciente/$id/chequeo'
    | '/paciente/$id/medicamentos'
    | '/paciente/$id/reporte'
    | '/paciente/$id/signos'
    | '/paciente/$id'
    | '/paciente/$id/escalas/jenkins'
    | '/paciente/$id/escalas/zarit'
    | '/paciente/$id/escalas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/app'
    | '/_app/paciente/nuevo'
    | '/_app/paciente/$id/bitacoras'
    | '/_app/paciente/$id/caidas'
    | '/_app/paciente/$id/chequeo'
    | '/_app/paciente/$id/medicamentos'
    | '/_app/paciente/$id/reporte'
    | '/_app/paciente/$id/signos'
    | '/_app/paciente/$id/'
    | '/_app/paciente/$id/escalas/jenkins'
    | '/_app/paciente/$id/escalas/zarit'
    | '/_app/paciente/$id/escalas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/nuevo': {
      id: '/_app/paciente/nuevo'
      path: '/paciente/nuevo'
      fullPath: '/paciente/nuevo'
      preLoaderRoute: typeof AppPacienteNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/': {
      id: '/_app/paciente/$id/'
      path: '/paciente/$id'
      fullPath: '/paciente/$id/'
      preLoaderRoute: typeof AppPacienteIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/signos': {
      id: '/_app/paciente/$id/signos'
      path: '/paciente/$id/signos'
      fullPath: '/paciente/$id/signos'
      preLoaderRoute: typeof AppPacienteIdSignosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/reporte': {
      id: '/_app/paciente/$id/reporte'
      path: '/paciente/$id/reporte'
      fullPath: '/paciente/$id/reporte'
      preLoaderRoute: typeof AppPacienteIdReporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/medicamentos': {
      id: '/_app/paciente/$id/medicamentos'
      path: '/paciente/$id/medicamentos'
      fullPath: '/paciente/$id/medicamentos'
      preLoaderRoute: typeof AppPacienteIdMedicamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/chequeo': {
      id: '/_app/paciente/$id/chequeo'
      path: '/paciente/$id/chequeo'
      fullPath: '/paciente/$id/chequeo'
      preLoaderRoute: typeof AppPacienteIdChequeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/caidas': {
      id: '/_app/paciente/$id/caidas'
      path: '/paciente/$id/caidas'
      fullPath: '/paciente/$id/caidas'
      preLoaderRoute: typeof AppPacienteIdCaidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/bitacoras': {
      id: '/_app/paciente/$id/bitacoras'
      path: '/paciente/$id/bitacoras'
      fullPath: '/paciente/$id/bitacoras'
      preLoaderRoute: typeof AppPacienteIdBitacorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/escalas/': {
      id: '/_app/paciente/$id/escalas/'
      path: '/paciente/$id/escalas'
      fullPath: '/paciente/$id/escalas/'
      preLoaderRoute: typeof AppPacienteIdEscalasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/escalas/zarit': {
      id: '/_app/paciente/$id/escalas/zarit'
      path: '/paciente/$id/escalas/zarit'
      fullPath: '/paciente/$id/escalas/zarit'
      preLoaderRoute: typeof AppPacienteIdEscalasZaritRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paciente/$id/escalas/jenkins': {
      id: '/_app/paciente/$id/escalas/jenkins'
      path: '/paciente/$id/escalas/jenkins'
      fullPath: '/paciente/$id/escalas/jenkins'
      preLoaderRoute: typeof AppPacienteIdEscalasJenkinsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppPacienteNuevoRoute: typeof AppPacienteNuevoRoute
  AppPacienteIdBitacorasRoute: typeof AppPacienteIdBitacorasRoute
  AppPacienteIdCaidasRoute: typeof AppPacienteIdCaidasRoute
  AppPacienteIdChequeoRoute: typeof AppPacienteIdChequeoRoute
  AppPacienteIdMedicamentosRoute: typeof AppPacienteIdMedicamentosRoute
  AppPacienteIdReporteRoute: typeof AppPacienteIdReporteRoute
  AppPacienteIdSignosRoute: typeof AppPacienteIdSignosRoute
  AppPacienteIdIndexRoute: typeof AppPacienteIdIndexRoute
  AppPacienteIdEscalasJenkinsRoute: typeof AppPacienteIdEscalasJenkinsRoute
  AppPacienteIdEscalasZaritRoute: typeof AppPacienteIdEscalasZaritRoute
  AppPacienteIdEscalasIndexRoute: typeof AppPacienteIdEscalasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppPacienteNuevoRoute: AppPacienteNuevoRoute,
  AppPacienteIdBitacorasRoute: AppPacienteIdBitacorasRoute,
  AppPacienteIdCaidasRoute: AppPacienteIdCaidasRoute,
  AppPacienteIdChequeoRoute: AppPacienteIdChequeoRoute,
  AppPacienteIdMedicamentosRoute: AppPacienteIdMedicamentosRoute,
  AppPacienteIdReporteRoute: AppPacienteIdReporteRoute,
  AppPacienteIdSignosRoute: AppPacienteIdSignosRoute,
  AppPacienteIdIndexRoute: AppPacienteIdIndexRoute,
  AppPacienteIdEscalasJenkinsRoute: AppPacienteIdEscalasJenkinsRoute,
  AppPacienteIdEscalasZaritRoute: AppPacienteIdEscalasZaritRoute,
  AppPacienteIdEscalasIndexRoute: AppPacienteIdEscalasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
